default: &default
  adapter: postgis
  encoding: unicode
  schema_search_path: "public,postgis"
  database: tournamentmanager
  pool: 5
  host: localhost
  username: postgres
  password:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
