# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdbc537d227f4ea5aa885f4235e3cc8a5ce80dd6a2ebe42cbfb74abfc99a8a38122991034f355ad4384350b59cda6c691654e6dd3222d7daf47bdd8e2c66a571

test:
  secret_key_base: 529a11e89cc3db7c650cdfd4e15c6b8816b5c885d80ae02d3cf41fc91cf52533bbb3187127614b892afe2158e00abf5a59a94121747dc50efc4433942cb96f3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
